export const module2 = [
  {
    id: 'latitude',
    name: 'Latitude',
    module: 2,
    difficulty: 'basic',
    emoji: '🔼',
    description: 'Angular distance north or south of the equator (0°–90°). Your latitude determines which stars can be circumpolar and the altitude of celestial poles above your horizon.',
    tooltip: 'Latitude tells you how far north or south of the equator you are, in degrees. The equator is 0°, the North Pole is 90°N, and the South Pole is 90°S. Your latitude also equals the altitude of the celestial pole above your horizon — super useful!',
    analogy: 'Latitude is like the "rows" on a giant grid covering Earth. The equator is row 0. London is in row 51 (north). Cape Town is in row 33 (south). The closer you are to a pole, the higher your "row number."',
    formula: null,
    relatedConcepts: ['longitude', 'observer-position', 'celestial-poles'],
    cameraPreset: { position: [0, 2, 5], target: [0, 0, 0] },
    visualizationKey: 'latitude',
    color: '#00E5FF',
  },
  {
    id: 'longitude',
    name: 'Longitude',
    module: 2,
    difficulty: 'basic',
    emoji: '◀▶',
    description: 'Angular distance east or west of the Prime Meridian (0°–180°). Your longitude determines your local time and directly affects Local Hour Angle.',
    tooltip: 'Longitude tells you how far east or west of the Prime Meridian (Greenwich, UK) you are. It\'s measured in degrees from 0° to 180° east or west. Every 15° of longitude = 1 hour of time difference!',
    analogy: 'Longitude is like the "columns" on Earth\'s grid. The Prime Meridian through Greenwich is column 0. New York is column 74W. Tokyo is column 139E. This is WHY New York is 5 hours behind London — they\'re 75° apart, and 75 ÷ 15 = 5 hours.',
    formula: 'LHA = GHA − West Longitude',
    relatedConcepts: ['latitude', 'prime-meridian', 'lha', 'gha'],
    cameraPreset: { position: [0, 1, 5], target: [0, 0, 0] },
    visualizationKey: 'longitude',
    color: '#FFB830',
  },
  {
    id: 'equator-parallels',
    name: 'Equator & Parallels',
    module: 2,
    difficulty: 'basic',
    emoji: '〰️',
    description: 'Circles of equal latitude. The equator is the only parallel that is also a great circle.',
    tooltip: 'Parallels (or parallels of latitude) are the horizontal lines on a globe at equal latitudes. The equator is the biggest one. Notice how parallels get smaller as you approach the poles — they\'re "parallel" to each other (never crossing).',
    analogy: 'Imagine slicing a boiled egg horizontally — each slice would be a different parallel of latitude! The largest slice in the middle is the equator. The slices near the ends are smaller, just like the latitude circles near the poles.',
    formula: null,
    relatedConcepts: ['latitude', 'great-circle', 'small-circle'],
    cameraPreset: { position: [0, 2, 5], target: [0, 0, 0] },
    visualizationKey: 'equator-parallels',
    color: '#00E5FF',
  },
  {
    id: 'great-circle',
    name: 'Great Circle',
    module: 2,
    difficulty: 'intermediate',
    emoji: '🌐',
    description: 'The shortest path between two points on a sphere. Every great circle divides the sphere into two equal halves. They are the "straight lines" of spherical geometry.',
    tooltip: 'A great circle is any circle on a sphere whose center is ALSO the center of the sphere. It\'s always the shortest path between two points on the sphere. The equator is a great circle. Every meridian is a great circle.',
    analogy: 'If you stretched a rubber band between London and New York on a globe, it would follow a great circle — curving up near Greenland. That\'s shorter than going in a straight line across on a flat map! That\'s why planes fly over Greenland on transatlantic flights.',
    formula: null,
    relatedConcepts: ['small-circle', 'rhumb-line', 'great-circle-route'],
    cameraPreset: { position: [0, 2, 5], target: [0, 0, 0] },
    visualizationKey: 'great-circle',
    color: '#00E5FF',
  },
  {
    id: 'small-circle',
    name: 'Small Circle',
    module: 2,
    difficulty: 'intermediate',
    emoji: '⭕',
    description: 'Any circle on a sphere whose plane does NOT pass through the center. All latitude parallels (except the equator) are small circles.',
    tooltip: 'A small circle is a circle on a sphere whose center is NOT the center of the sphere. All parallels of latitude (except the equator) are small circles. They\'re "smaller" than great circles when measured against the full sphere.',
    analogy: 'Think of slicing an apple. If you slice through the exact center, you get the biggest circle (great circle). Any other slice creates a smaller circle. Latitude parallels (except the equator) are like those off-center slices.',
    formula: null,
    relatedConcepts: ['great-circle', 'latitude', 'equator-parallels'],
    cameraPreset: { position: [0, 2, 5], target: [0, 0, 0] },
    visualizationKey: 'small-circle',
    color: '#8B7CF8',
  },
  {
    id: 'declination',
    name: 'Declination',
    module: 2,
    difficulty: 'intermediate',
    emoji: '🌟',
    description: 'The celestial equivalent of latitude. Measured in degrees north (+) or south (–) of the celestial equator. The Sun\'s declination changes from +23.5° (June) to –23.5° (December).',
    tooltip: 'Declination is "latitude for the sky" — how far north or south of the celestial equator a star is. The Sun\'s declination changes throughout the year (from +23.5° in summer to −23.5° in winter). Most stars have nearly constant declinations.',
    analogy: 'If latitude is your address on Earth (north/south), then declination is a star\'s address in the sky (north/south of the celestial equator). The Sun\'s declination changes as Earth orbits — that\'s what causes our seasons!',
    formula: 'Dec = +23.5° (summer solstice) to −23.5° (winter solstice)',
    relatedConcepts: ['celestial-equator', 'gha', 'pzx-polar-distance'],
    cameraPreset: { position: [0, 2, 8], target: [0, 0, 0] },
    visualizationKey: 'declination',
    color: '#FFB830',
  },
  {
    id: 'gha',
    name: 'Greenwich Hour Angle',
    module: 2,
    difficulty: 'intermediate',
    emoji: '🕐',
    description: 'How far WEST the body is from the Prime Celestial Meridian, measured along the celestial equator (0°–360° westward). GHA increases as Earth rotates east.',
    tooltip: 'GHA (Greenwich Hour Angle) measures how far WESTWARD a celestial body is from the Greenwich sky meridian, going all the way around (0° to 360°). As Earth spins eastward, GHA increases by about 15° per hour. The Nautical Almanac lists GHA for every hour of every day.',
    analogy: 'Imagine the Sun is a runner on a circular track around the sky. GHA is how far the runner has gone past the starting line (Greenwich meridian), always counting westward. It increases 15° per hour as Earth spins.',
    formula: 'GHA increases ~15° per hour (360° in 24 hours)',
    relatedConcepts: ['lha', 'sha', 'first-point-of-aries', 'longitude'],
    cameraPreset: { position: [0, 3, 8], target: [0, 0, 0] },
    visualizationKey: 'gha',
    color: '#FFB830',
  },
  {
    id: 'lha',
    name: 'Local Hour Angle',
    module: 2,
    difficulty: 'intermediate',
    emoji: '🕑',
    description: 'How far WEST the body is from YOUR meridian. The key input to the altitude calculation. When LHA = 0°, the body is on your meridian (local noon for the Sun).',
    tooltip: 'LHA (Local Hour Angle) is like GHA but measured from YOUR meridian instead of Greenwich. When LHA = 0°, the body is crossing your meridian — that\'s local noon for the Sun! LHA is the most important input for calculating where a body should be in your sky.',
    analogy: 'GHA is the Sun\'s position measured from the global "start line" (Greenwich). LHA is the Sun\'s position from YOUR personal "start line" (your meridian). They\'re the same idea, just different reference points.',
    formula: 'LHA = GHA − West Longitude (or GHA + East Longitude)',
    relatedConcepts: ['gha', 'meridian', 'altitude-equation', 'longitude'],
    cameraPreset: { position: [0, 3, 8], target: [0, 0, 0] },
    visualizationKey: 'lha',
    color: '#00E5FF',
  },
  {
    id: 'sha',
    name: 'Sidereal Hour Angle',
    module: 2,
    difficulty: 'advanced',
    emoji: '✨',
    description: "A star's fixed position west of the First Point of Aries. Unlike GHA (which changes hourly), SHA is nearly constant for a star. GHA★ = GHA♈ + SHA.",
    tooltip: 'SHA (Sidereal Hour Angle) is a star\'s permanent "sky address" — how far west it is from the First Point of Aries. Unlike GHA (which changes every hour), SHA barely changes over years. To find a star\'s current GHA, add its SHA to the GHA of Aries.',
    analogy: 'GHA is like a store\'s current cash register balance (changes all the time). SHA is like the store\'s fixed street address — it stays the same. You use SHA as the fixed starting point, then add the changing GHA of Aries to get the current position.',
    formula: 'GHA★ = GHA♈ + SHA',
    relatedConcepts: ['gha', 'right-ascension', 'first-point-of-aries'],
    cameraPreset: { position: [0, 3, 8], target: [0, 0, 0] },
    visualizationKey: 'sha',
    color: '#8B7CF8',
  },
  {
    id: 'right-ascension',
    name: 'Right Ascension',
    module: 2,
    difficulty: 'advanced',
    emoji: '🔭',
    description: 'Like SHA but measured EASTWARD in hours (0h–24h). Used in astronomy. RA = 360° – SHA. The navigator uses SHA; the astronomer uses RA.',
    tooltip: 'Right Ascension (RA) is how astronomers measure a star\'s position going EASTWARD from the First Point of Aries, in hours (0h to 24h). Navigators use SHA (going westward, in degrees). They measure the same thing, just in opposite directions and different units.',
    analogy: 'Imagine reading a clock. You can say it\'s "3 hours clockwise from 12" or "21 hours counter-clockwise from 12" — both describe the same position. RA is like going counter-clockwise; SHA is like going clockwise. Same star, different systems.',
    formula: 'RA (hours) = (360° − SHA) ÷ 15',
    relatedConcepts: ['sha', 'first-point-of-aries', 'gha'],
    cameraPreset: { position: [0, 3, 8], target: [0, 0, 0] },
    visualizationKey: 'right-ascension',
    color: '#FFB830',
  },
  {
    id: 'hour-circle',
    name: 'Hour Circle',
    module: 2,
    difficulty: 'intermediate',
    emoji: '⭕',
    description: 'A great circle on the celestial sphere passing through both Celestial Poles and the body. Like a meridian of longitude, but for the sky.',
    tooltip: 'An hour circle is a great circle passing through both celestial poles AND through a specific star or body. It\'s exactly like a meridian of longitude but on the celestial sphere. Declination is measured along the hour circle from the celestial equator to the body.',
    analogy: 'Meridians on Earth run from the North Pole to the South Pole. Hour circles do the same thing on the celestial sphere — they run from the North Celestial Pole to the South Celestial Pole, passing through whatever star you\'re interested in.',
    formula: null,
    relatedConcepts: ['declination', 'gha', 'sha', 'celestial-poles'],
    cameraPreset: { position: [0, 3, 8], target: [0, 0, 0] },
    visualizationKey: 'hour-circle',
    color: '#8B7CF8',
  },
  {
    id: 'first-point-of-aries',
    name: 'First Point of Aries ♈',
    module: 2,
    difficulty: 'advanced',
    emoji: '♈',
    description: 'The zero-reference point of the celestial coordinate system. Where the Sun crosses the celestial equator at the March equinox. GHA♈ and SHA are measured from this point.',
    tooltip: 'The First Point of Aries (♈) is the "zero marker" for the sky\'s coordinate system. It\'s the point on the celestial equator where the Sun crosses from south to north each March (the spring equinox). All hour angles (GHA, SHA) are measured from this point.',
    analogy: 'Every ruler needs a starting point marked "0". For measuring positions in the sky, ancient astronomers chose the location of the Sun at the spring equinox as their zero marker — the First Point of Aries. It\'s the ruler\'s starting point for the entire celestial coordinate system.',
    formula: 'GHA★ = GHA♈ + SHA★',
    relatedConcepts: ['sha', 'gha', 'celestial-equator'],
    cameraPreset: { position: [0, 2, 8], target: [0, 0, 0] },
    visualizationKey: 'first-point-of-aries',
    color: '#FFB830',
  },
  {
    id: 'vertical-circle',
    name: 'Vertical Circle',
    module: 2,
    difficulty: 'intermediate',
    emoji: '⭕',
    description: 'Any great circle on the celestial sphere that passes through your Zenith (and Nadir). Altitude is measured along the vertical circle from the horizon to the body.',
    tooltip: 'A vertical circle is any great circle on the celestial sphere that passes through your zenith. Each line from the very top of the sky-bubble down through any star is a vertical circle. Altitude is measured along it, from horizon up to the body.',
    analogy: 'Think of peeling an orange. Each "peel strip" from top to bottom represents a vertical circle. They all meet at the zenith (top) and nadir (bottom). You measure how high a star is by how far up its vertical circle it sits.',
    formula: null,
    relatedConcepts: ['zenith', 'altitude', 'prime-vertical', 'azimuth'],
    cameraPreset: { position: [0, 3, 11], target: [0, 0, 0] },
    visualizationKey: 'vertical-circle',
    color: '#00E5FF',
  },
  {
    id: 'prime-vertical',
    name: 'Prime Vertical',
    module: 2,
    difficulty: 'intermediate',
    emoji: '↔️',
    description: 'The vertical circle through East and West points. When a star crosses the prime vertical, it\'s at its maximum azimuth deviation.',
    tooltip: 'The prime vertical is the special vertical circle that runs exactly east-west through your zenith. It\'s perpendicular to your meridian. When a star crosses the prime vertical, navigators measure the star\'s azimuth very accurately.',
    analogy: 'Your meridian goes north–south, the prime vertical goes east–west — they form a perpendicular cross in the sky meeting right at your zenith. Like the x and y axes on a graph, but drawn on the sky dome.',
    formula: null,
    relatedConcepts: ['vertical-circle', 'meridian', 'azimuth'],
    cameraPreset: { position: [4, 2, 11], target: [0, 0, 0] },
    visualizationKey: 'prime-vertical',
    color: '#FFB830',
  },
  {
    id: 'altitude',
    name: 'Altitude',
    module: 2,
    difficulty: 'basic',
    emoji: '📐',
    description: 'The angle of a celestial body above your horizon, measured along the vertical circle (0° at horizon, 90° at zenith). The sextant measures altitude directly.',
    tooltip: 'Altitude (Hc or Ho) is how HIGH a celestial body is above your horizon, measured in degrees. Horizon = 0°, straight up (zenith) = 90°. A sextant is the instrument sailors use to measure this angle. This is the KEY measurement in celestial navigation!',
    analogy: 'Altitude is like measuring how high something is above the ground, but using angles instead of meters. If a star is halfway between the horizon and straight overhead, its altitude is 45°. If it\'s barely peeking over the horizon, altitude is near 0°.',
    formula: 'h (altitude) + ZD (zenith distance) = 90°',
    relatedConcepts: ['zenith-distance', 'azimuth', 'sextant-ho', 'vertical-circle'],
    cameraPreset: { position: [3, 2, 3], target: [0, 0, 0] },
    visualizationKey: 'altitude',
    color: '#00E5FF',
  },
  {
    id: 'zenith-distance',
    name: 'Zenith Distance',
    module: 2,
    difficulty: 'intermediate',
    emoji: '📏',
    description: 'The angular distance from your Zenith to the body. Directly related to altitude: they always add up to 90°. ZD equals the radius of your circle of equal altitude on Earth\'s surface.',
    tooltip: 'Zenith Distance (ZD) is how far a body is from directly overhead (your zenith), measured in degrees. It\'s simply 90° minus the altitude. If altitude is 60°, then ZD is 30°. ZD is also the distance from your position to the body\'s GP on Earth\'s surface (in degrees of arc).',
    analogy: 'If altitude is how high a star is (measured from horizon), zenith distance is how far it is from straight overhead. They always add up to 90°, like the two angles in a right triangle that aren\'t the 90° corner.',
    formula: 'ZD = 90° − h',
    relatedConcepts: ['altitude', 'zenith', 'position-circle'],
    cameraPreset: { position: [3, 2, 3], target: [0, 0, 0] },
    visualizationKey: 'zenith-distance',
    color: '#FFB830',
  },
  {
    id: 'azimuth',
    name: 'Azimuth',
    module: 2,
    difficulty: 'basic',
    emoji: '🧭',
    description: 'The compass bearing of a celestial body. Measured clockwise from North along the horizon (0°–360°). Combined with altitude, azimuth fully describes where a body is in your sky.',
    tooltip: 'Azimuth is the DIRECTION to a celestial body, measured as a compass bearing. North = 0°, East = 090°, South = 180°, West = 270°. Azimuth + Altitude together fully describe exactly where to look in the sky to find any star or planet.',
    analogy: 'Azimuth is just like using a compass. "The Sun is at 180° azimuth" means it\'s due south. "The North Star is at 000° azimuth" means it\'s due north. A helicopter pilot gives both altitude angle AND azimuth to describe exactly where to look for something in the sky.',
    formula: null,
    relatedConcepts: ['altitude', 'pzx-azimuth', 'bearing'],
    cameraPreset: { position: [3, 0.5, 3], target: [0, 0, 0] },
    visualizationKey: 'azimuth',
    color: '#FFB830',
  },
  {
    id: 'bearing',
    name: 'Bearing & Amplitude',
    module: 2,
    difficulty: 'advanced',
    emoji: '📡',
    description: 'Bearing: the compass direction to a body. Amplitude: the angular distance of a body from due East or West at rising/setting. Used to check compass deviation.',
    tooltip: 'Bearing is the compass direction to something. Amplitude is a specific bearing measured from due East or West — used when a body is right on the horizon (rising or setting). If the Sun rises at exactly East, amplitude = 0° and your compass is correct!',
    analogy: 'Sailors used to check their compass by noting where the Sun rose or set. If the Sun rose exactly east and the compass read exactly 090°, the compass was accurate. Any difference (called "compass error") meant the compass needed adjustment.',
    formula: null,
    relatedConcepts: ['azimuth', 'horizon', 'rising-setting'],
    cameraPreset: { position: [3, 0.5, 3], target: [0, 0, 0] },
    visualizationKey: 'bearing',
    color: '#FFB830',
  },
]
