export const module7 = [
  {
    id: 'twilight-zones',
    name: 'Twilight Zones',
    module: 7,
    difficulty: 'basic',
    emoji: '🌆',
    description: 'Navigator\'s gold: Nautical Twilight (Sun 6°–12° below horizon). Dark enough to see stars, light enough to see the horizon. The prime window for star sights.',
    tooltip: 'Twilight has three zones: Civil (Sun 0°–6° below horizon — still quite bright), Nautical (Sun 6°–12° below — dark enough to see bright stars, still light enough to see the horizon), and Astronomical (12°–18° — truly dark). Navigators LOVE nautical twilight — it\'s the only time you can see both stars AND the horizon simultaneously!',
    analogy: 'During the day, stars are invisible (sky too bright). At night, the horizon disappears (too dark to see it). Nautical twilight is the 20-minute sweet spot twice a day when you can see both stars AND the horizon — like Goldilocks: not too bright, not too dark, just right!',
    formula: 'Civil: Sun 0°–6° below horizon\nNautical: Sun 6°–12° below\nAstronomical: Sun 12°–18° below',
    relatedConcepts: ['terminator', 'altitude', 'rising-setting'],
    cameraPreset: { position: [3, 2, 4], target: [0, 0, 0] },
    visualizationKey: 'twilight-zones',
    color: '#FF8C42',
  },
  {
    id: 'terminator',
    name: 'Terminator',
    module: 7,
    difficulty: 'basic',
    emoji: '🌓',
    description: 'The moving boundary between the sunlit and dark sides of Earth. Where you are relative to the terminator determines which type of twilight you\'re in.',
    tooltip: 'The terminator is the moving shadow line on Earth that separates the sunlit side from the dark side. It\'s not a sharp line in reality — it\'s actually a wide band of twilight. You can see the terminator clearly from space, and it always runs roughly north-south on Earth\'s surface.',
    analogy: 'Think of Earth like a rotating ball under a flashlight. The terminator is the edge of the flashlight\'s beam — half the ball is lit, half is dark. The shadow edge slowly moves around Earth as it spins (or you can think of the flashlight — the Sun — slowly moving around the ball).',
    formula: null,
    relatedConcepts: ['twilight-zones', 'diurnal-motion'],
    cameraPreset: { position: [4, 1, 4], target: [0, 0, 0] },
    visualizationKey: 'terminator',
    color: '#FF8C42',
  },
]
