export const module3 = [
  {
    id: 'diurnal-motion',
    name: 'Diurnal Motion',
    module: 3,
    difficulty: 'basic',
    emoji: '🔄',
    description: 'The apparent daily rotation of the sky from east to west, caused by Earth\'s west-to-east rotation. Every star traces a circle parallel to the celestial equator every 24 hours.',
    tooltip: 'Diurnal motion is the apparent daily movement of stars across the sky from east to west. It\'s not the stars moving — it\'s Earth spinning! Earth rotates eastward, which makes stars appear to move westward. Every star completes one full circle every 24 hours.',
    analogy: 'Sit in a rotating office chair and watch the room "spin" around you. Earth is the chair, and the stars are the room. Earth spins eastward, so the stars appear to sweep westward across the sky. Rise in the east, set in the west!',
    formula: 'Stars move ~15° per hour (360° ÷ 24 hours)',
    relatedConcepts: ['celestial-sphere', 'circumpolar-star', 'sidereal-solar-time'],
    cameraPreset: { position: [0, 3, 8], target: [0, 0, 0] },
    visualizationKey: 'diurnal-motion',
    color: '#FFB830',
  },
  {
    id: 'annual-motion',
    name: 'Annual Motion (Ecliptic)',
    module: 3,
    difficulty: 'intermediate',
    emoji: '🌞',
    description: 'Earth\'s orbit makes the Sun appear to move along the Ecliptic — a great circle tilted 23.5° to the celestial equator. This tilt causes seasons.',
    tooltip: 'As Earth orbits the Sun over a year, the Sun appears to slowly move through the stars along a tilted path called the Ecliptic. This path is tilted 23.5° to the celestial equator — that tilt is what causes seasons. The Sun takes 365 days to go all the way around.',
    analogy: 'If you walk around a lamp in a room, the lamp appears to move against the background. You\'re Earth, the lamp is the Sun, and the background is the stars. From Earth, the Sun appears to slowly travel through different star constellations throughout the year.',
    formula: 'Sun moves ~1° per day along ecliptic (360° ÷ 365 days)',
    relatedConcepts: ['declination', 'obliquity', 'equinox'],
    cameraPreset: { position: [0, 3, 8], target: [0, 0, 0] },
    visualizationKey: 'annual-motion',
    color: '#FFB830',
  },
  {
    id: 'rising-setting',
    name: 'Rising, Setting, Transit',
    module: 3,
    difficulty: 'basic',
    emoji: '🌅',
    description: 'Rising: when a body appears above the East horizon. Setting: disappears below West horizon. Transit: crosses your meridian at max altitude.',
    tooltip: 'Every celestial body goes through three key moments each day: Rising (appears in the east), Transit (crosses your meridian, highest point in sky), and Setting (disappears in the west). The Sun\'s transit is local noon — its highest point and due south (in northern hemisphere).',
    analogy: 'Like a performer in a show: they enter from stage left (rising in east), reach center stage (transit, highest altitude), then exit stage right (setting in west). The Sun does this show every single day!',
    formula: null,
    relatedConcepts: ['diurnal-motion', 'lan', 'azimuth', 'altitude'],
    cameraPreset: { position: [4, 1, 4], target: [0, 0, 0] },
    visualizationKey: 'rising-setting',
    color: '#FF6B6B',
  },
  {
    id: 'upper-lower-transit',
    name: 'Upper & Lower Transit',
    module: 3,
    difficulty: 'intermediate',
    emoji: '↕️',
    description: 'Upper transit: the body\'s highest daily altitude (crossing meridian above the pole). Lower transit: the body\'s lowest altitude (crossing meridian below the pole). Both visible for circumpolar stars.',
    tooltip: 'A circumpolar star (one that never sets) crosses the meridian twice each day. Upper transit is when it\'s highest (above the celestial pole). Lower transit is when it\'s lowest (below the pole but still above your horizon). Both crossings can be used for navigation.',
    analogy: 'Imagine a star attached to a merry-go-round that spins around the North Star. Twice per day it crosses your north-south meridian line — once at the top of its circle (upper transit) and once at the bottom (lower transit).',
    formula: null,
    relatedConcepts: ['transit', 'circumpolar-star', 'meridian'],
    cameraPreset: { position: [0, 4, 3], target: [0, 0, 0] },
    visualizationKey: 'upper-lower-transit',
    color: '#00E5FF',
  },
  {
    id: 'culmination',
    name: 'Culmination',
    module: 3,
    difficulty: 'basic',
    emoji: '🏆',
    description: 'Another term for upper transit — the moment a body reaches its greatest altitude. The Sun culminates at Local Apparent Noon, the ideal moment for a noon sight.',
    tooltip: 'Culmination means a body reaching its HIGHEST point in the sky — upper transit. For the Sun, this happens at Local Apparent Noon (LAN), and it\'s the best time to take a noon sight to find your latitude. At culmination, the body is exactly on your meridian.',
    analogy: 'Think of a basketball player\'s jump shot — the ball reaches its highest point (culmination) before coming back down. The Sun does the same thing in the sky each day, reaching its peak (culmination) at noon.',
    formula: null,
    relatedConcepts: ['upper-lower-transit', 'lan', 'altitude'],
    cameraPreset: { position: [2, 4, 3], target: [0, 0, 0] },
    visualizationKey: 'culmination',
    color: '#FFB830',
  },
  {
    id: 'circumpolar-star',
    name: 'Circumpolar Star',
    module: 3,
    difficulty: 'intermediate',
    emoji: '🌀',
    description: 'A star that never rises or sets — it circles the pole without touching the horizon. Whether a star is circumpolar depends on your latitude.',
    tooltip: 'A circumpolar star is one that NEVER dips below the horizon — it circles the celestial pole all day, every day. Whether a star is circumpolar for YOU depends on your latitude. The higher your latitude, the more stars are circumpolar. At the poles, ALL stars are circumpolar!',
    analogy: 'At the North Pole, all stars circle overhead and none rise or set. In London (51°N), stars close to Polaris are circumpolar — they circle the North Star without setting. In the tropics, only stars very close to the poles are circumpolar.',
    formula: 'Star is circumpolar if: Dec > (90° − Lat)',
    relatedConcepts: ['celestial-poles', 'diurnal-motion', 'latitude'],
    cameraPreset: { position: [0, 4, 4], target: [0, 0, 0] },
    visualizationKey: 'circumpolar-star',
    color: '#8B7CF8',
  },
  {
    id: 'obliquity',
    name: 'Obliquity of the Ecliptic',
    module: 3,
    difficulty: 'intermediate',
    emoji: '↗️',
    description: 'The tilt of Earth\'s axis — 23.5° — which causes the ecliptic to be inclined to the celestial equator by the same amount. This is WHY we have seasons.',
    tooltip: 'Earth\'s axis isn\'t straight up and down — it\'s tilted 23.5° from vertical. This tilt is the "obliquity of the ecliptic." It\'s why the Sun\'s declination changes throughout the year (+23.5° in summer, −23.5° in winter), and it\'s the direct cause of our four seasons.',
    analogy: 'Picture a spinning top that\'s not perfectly vertical — it\'s leaning slightly. Earth is like that top, tilted 23.5°. When the Northern Hemisphere tilts toward the Sun, it\'s summer there (more direct sunlight). When it tilts away, it\'s winter.',
    formula: 'Obliquity ≈ 23.5° (23° 26\')',
    relatedConcepts: ['declination', 'annual-motion', 'celestial-equator'],
    cameraPreset: { position: [0, 3, 8], target: [0, 0, 0] },
    visualizationKey: 'obliquity',
    color: '#FFB830',
  },
  {
    id: 'lan',
    name: 'Local Apparent Noon',
    module: 3,
    difficulty: 'intermediate',
    emoji: '🌞',
    description: 'The moment the Sun transits your meridian — crosses due South. The Sun reaches its highest altitude. By measuring this altitude, you can calculate your latitude directly.',
    tooltip: 'Local Apparent Noon (LAN) is when the Sun crosses YOUR meridian — the moment it\'s exactly due south (in northern hemisphere) and at its highest point. By measuring the Sun\'s altitude at this moment, you can calculate your latitude. This is the classic "noon sight" used by navigators for centuries!',
    analogy: 'At noon in a sunny location, your shadow is shortest and points directly north (in the northern hemisphere). That\'s because the Sun is at its highest — it\'s crossed your meridian. Sailors use a sextant to measure exactly how high the Sun is at this moment to find their latitude.',
    formula: 'Lat = 90° − Altitude + Declination (simplified)',
    relatedConcepts: ['culmination', 'meridian', 'altitude', 'declination'],
    cameraPreset: { position: [3, 3, 3], target: [0, 0, 0] },
    visualizationKey: 'lan',
    color: '#FFB830',
  },
  {
    id: 'sidereal-solar-time',
    name: 'Sidereal vs Solar Time',
    module: 3,
    difficulty: 'advanced',
    emoji: '⏱️',
    description: 'A sidereal day is relative to the stars (23h 56m). A solar day is relative to the Sun (24h). Slightly different because Earth is also orbiting.',
    tooltip: 'A sidereal day (star day) is 23 hours, 56 minutes — how long Earth takes to spin exactly 360° relative to the stars. A solar day is 24 hours — how long between two consecutive noons. The 4-minute difference exists because Earth also moves along its orbit, so it needs to spin a tiny bit extra to face the Sun.',
    analogy: 'Imagine spinning on the spot while slowly walking around a lamp. To face the lamp again, you need to spin a bit more than 360° — because the lamp moved relative to you as you walked. Stars (the "fixed background") come back after 360°, but the Sun needs a little extra.',
    formula: '1 solar day = 1 sidereal day + ~4 minutes',
    relatedConcepts: ['diurnal-motion', 'gha', 'first-point-of-aries'],
    cameraPreset: { position: [0, 3, 8], target: [0, 0, 0] },
    visualizationKey: 'sidereal-solar-time',
    color: '#8B7CF8',
  },
  {
    id: 'equation-of-time',
    name: 'Equation of Time',
    module: 3,
    difficulty: 'advanced',
    emoji: '📊',
    description: 'The difference between Mean Solar Time and Apparent Solar Time. Ranges from –16 to +14 minutes. Applied to sun sights for precise navigation.',
    tooltip: 'The equation of time is the difference between "clock noon" and "Sun noon." The real Sun doesn\'t move at a perfectly even speed — sometimes it\'s "ahead" of clock noon, sometimes "behind." This correction (up to 16 minutes!) must be applied for precise celestial navigation.',
    analogy: 'Imagine a race between two runners — one runs at perfectly constant speed (the "mean sun"), and one speeds up and slows down (the real Sun). Sometimes the real Sun is ahead, sometimes behind. The "equation of time" is how far apart they are at any moment.',
    formula: 'Apparent Solar Time = Mean Solar Time ± Equation of Time',
    relatedConcepts: ['lan', 'sidereal-solar-time', 'gha'],
    cameraPreset: { position: [0, 3, 8], target: [0, 0, 0] },
    visualizationKey: 'equation-of-time',
    color: '#FF6B6B',
  },
]
