export const module5 = [
  {
    id: 'geographic-position',
    name: 'Geographic Position (GP)',
    module: 5,
    difficulty: 'intermediate',
    emoji: '📍',
    description: 'The point on Earth\'s surface directly below a celestial body. If you were at the GP, the body would be at your zenith.',
    tooltip: 'The Geographic Position (GP) is the spot on Earth directly below a celestial body — where a line from the body, through Earth\'s center, hits Earth\'s surface. If you stood exactly at a body\'s GP, it would be directly overhead (at your zenith). The Sun\'s GP is called its sub-solar point.',
    analogy: 'On a sunny day, look at your shadow — that\'s YOU on the ground. The Sun\'s "shadow" (if Earth were transparent) would be the Sun\'s Geographic Position. It moves westward across Earth as Earth spins.',
    formula: 'GP Latitude = Declination, GP Longitude = 360° − GHA (W)',
    process: [
      { title: 'Find Declination', detail: 'Look up the body\'s declination in the Nautical Almanac for the exact time of observation. This becomes the GP\'s latitude.' },
      { title: 'Find GHA', detail: 'Look up the body\'s Greenwich Hour Angle (GHA). This determines the GP\'s longitude (lon = -GHA, or equivalently 360° - GHA west).' },
      { title: 'Plot the GP', detail: 'Mark this lat/lon on the Earth. The Sun\'s GP moves westward at 15° per hour as Earth rotates.' },
    ],
    relatedConcepts: ['position-circle', 'zenith', 'declination', 'gha'],
    cameraPreset: { position: [2, 2, 5], target: [0, 0, 0] },
    visualizationKey: 'geographic-position',
    color: '#FFB830',
  },
  {
    id: 'position-circle',
    name: 'Circle of Equal Altitude',
    module: 5,
    difficulty: 'advanced',
    emoji: '⭕',
    description: 'Every observer on this circle sees the body at the same altitude. ZD equals the circle\'s angular radius. You\'re somewhere on this circle.',
    tooltip: 'A Circle of Equal Altitude (position circle) is a circle on Earth where everyone sees a specific star at the same altitude at the same moment. If you observe the Sun at 45°, you\'re somewhere on a circle around the Sun\'s GP. The circle\'s radius (in degrees) = 90° − 45° = 45° (about 2,700 nautical miles!)',
    analogy: 'Imagine a glowing ball held in the air. Everyone standing in a circle around the ball sees it at the same angle. Make the circle bigger (move everyone farther away) and the angle gets smaller. Your position circle is like that — a huge circle around the Sun\'s position on Earth.',
    formula: 'Circle radius (ZD) = 90° − observed altitude',
    process: [
      { title: 'Measure Altitude (Ho)', detail: 'Use a sextant to measure the body\'s altitude above the horizon. This is your Observed Altitude, Ho.' },
      { title: 'Compute Zenith Distance', detail: 'ZD = 90° − Ho. This angular distance is the radius (in degrees) of your position circle.' },
      { title: 'Draw the Circle', detail: 'Center on the body\'s GP, with radius = ZD (in degrees of arc, where 1° = 60 nautical miles). YOU are somewhere on this circle.' },
    ],
    relatedConcepts: ['geographic-position', 'lop', 'zenith-distance', 'intercept'],
    cameraPreset: { position: [0, 4, 3], target: [0, 0, 0] },
    visualizationKey: 'position-circle',
    color: '#00E5FF',
  },
  {
    id: 'lop',
    name: 'Line of Position (LOP)',
    module: 5,
    difficulty: 'intermediate',
    emoji: '📏',
    description: 'A small arc segment of the position circle (near estimated position) shown as a straight line. You\'re somewhere on this line.',
    tooltip: 'A Line of Position (LOP) is a short, straight portion of your huge position circle, drawn near your estimated position. Since your position circle is thousands of miles across, you only care about the tiny bit near where you think you are. You are SOMEWHERE on this line.',
    analogy: 'Imagine your position circle is the edge of a giant pizza. You\'re somewhere on the crust. But you know roughly where on the crust you are (your estimated position), so you only need to draw the few inches of crust near you — that\'s your LOP.',
    process: [
      { title: 'Identify Approximate Position', detail: 'Use Dead Reckoning (DR) — your last known position plus course/speed/time — to know roughly where you are.' },
      { title: 'Compute Body Azimuth', detail: 'Calculate the azimuth (bearing) to the body from your DR position using the PZX triangle.' },
      { title: 'Draw LOP Perpendicular to Azimuth', detail: 'The LOP is always perpendicular to the bearing of the body. Draw a short straight line crossing the position circle near your DR.' },
    ],
    relatedConcepts: ['position-circle', 'intercept', 'fix'],
    cameraPreset: { position: [3, 2, 4], target: [0, 0, 0] },
    visualizationKey: 'lop',
    color: '#00E676',
  },
  {
    id: 'intercept',
    name: 'Intercept Method',
    module: 5,
    difficulty: 'advanced',
    emoji: '🎯',
    description: 'Compare Ho (observed) with Hc (calculated). The difference (in arcminutes = nm) tells how to shift the LOP. Toward body if Ho > Hc.',
    tooltip: 'The Intercept Method (Marcq St Hilaire) compares your OBSERVED altitude (Ho, from sextant) to your CALCULATED altitude (Hc, from the PZX triangle formula). The difference — called the intercept — tells you which direction to shift your LOP. Rule: "Ho Mo To" — if Ho is More than Hc, shift Toward the body.',
    analogy: 'You\'re trying to find your friend in a city. You guess they\'re at 5th Avenue (assumed position), and calculate they should be about 3 blocks north of you (Hc). But when you look, they\'re actually 5 blocks north (Ho). The 2-block difference tells you to shift your estimate northward, toward your friend.',
    formula: 'Intercept a = Ho − Hc (in arcminutes = nautical miles)\nHo > Hc → Toward body; Ho < Hc → Away from body',
    process: [
      { title: 'Pick Assumed Position (AP)', detail: 'Choose a convenient AP near your DR. (Often whole-degree lat/lon to simplify almanac lookup.)' },
      { title: 'Compute Hc & Az', detail: 'Use the PZX triangle: sin(Hc) = sinφ·sinδ + cosφ·cosδ·cos(LHA). Also compute the azimuth Az.' },
      { title: 'Measure Ho', detail: 'Take an actual sextant sight to get the observed altitude Ho. Apply corrections (dip, refraction, semi-diameter).' },
      { title: 'Calculate Intercept', detail: 'a = Ho − Hc, in arcminutes (each minute = 1 nautical mile of distance).' },
      { title: 'Plot LOP', detail: 'From AP, move along the azimuth line by the intercept distance — TOWARD the GP if Ho > Hc, AWAY if Ho < Hc. Draw the LOP perpendicular at that point.' },
    ],
    relatedConcepts: ['lop', 'position-circle', 'altitude-equation', 'fix'],
    cameraPreset: { position: [3, 2, 4], target: [0, 0, 0] },
    visualizationKey: 'intercept',
    color: '#FF6B6B',
  },
  {
    id: 'running-fix',
    name: 'Running Fix',
    module: 5,
    difficulty: 'advanced',
    emoji: '🏃',
    description: 'Two LOPs from same body at different times. The first LOP is advanced along course/speed. The intersection is a running fix.',
    tooltip: 'A running fix uses two sights of the same body taken hours apart. The first LOP is "advanced" (moved) along your course and speed to match the time of the second sight. Where the two LOPs now cross is your running fix — your best estimated position.',
    analogy: 'Imagine you take a photo of a landmark at 10am (LOP 1). You sail for 3 hours. Take another photo at 1pm (LOP 2). The first photo\'s direction line needs to be "moved" to account for your 3-hour journey. Where the adjusted line meets the new line is where you are.',
    process: [
      { title: 'First Sight @ T1', detail: 'Take a sight at time T1 and plot the first LOP (LOP-1).' },
      { title: 'Sail with Known Course/Speed', detail: 'Continue on a known course at known speed for time interval Δt = T2 − T1.' },
      { title: 'Second Sight @ T2', detail: 'Take a second sight at time T2 (could be same body or different) and plot LOP-2.' },
      { title: 'Advance LOP-1', detail: 'Move LOP-1 forward along the course direction by distance = speed × Δt. Keep LOP-1\'s orientation unchanged.' },
      { title: 'Intersection = Running Fix', detail: 'The intersection of the advanced LOP-1 with LOP-2 is your Running Fix at time T2.' },
    ],
    relatedConcepts: ['lop', 'fix', 'intercept'],
    cameraPreset: { position: [3, 2, 4], target: [0, 0, 0] },
    visualizationKey: 'running-fix',
    color: '#FFB830',
  },
  {
    id: 'fix',
    name: 'Fix (Two or More LOPs)',
    module: 5,
    difficulty: 'intermediate',
    emoji: '📌',
    description: 'Two LOPs from two different bodies crossing gives you a fix — a specific position. Three LOPs form a small triangle (cocked hat); position is within it.',
    tooltip: 'A FIX is your actual calculated position! Two LOPs from two different stars crossing gives you a point — that\'s where you are. Three LOPs form a small triangle (called a "cocked hat") — you\'re somewhere inside it. More LOPs = smaller triangle = more accurate fix.',
    analogy: 'Two witnesses say they saw someone at "the corner of 5th and Main." One LOP says "on 5th Street," the other says "on Main Street." Where the two streets cross is your fix! Add a third witness (LOP) and you get a small triangle instead of a perfect point — reality is never perfect.',
    process: [
      { title: 'Take Two Sights', detail: 'Observe TWO different celestial bodies at nearly the same time (e.g., Sun & Moon, or two stars during twilight).' },
      { title: 'Compute Each GP', detail: 'For each body, get GHA & Dec from almanac → GP at (Dec, -GHA).' },
      { title: 'Compute Each Hc, Az', detail: 'Using your assumed position and PZX formula, compute the predicted altitude (Hc) and azimuth for each body.' },
      { title: 'Plot Each LOP', detail: 'For each body, calculate intercept (Ho − Hc) and plot the LOP perpendicular to the body\'s azimuth, offset from AP by the intercept.' },
      { title: 'Find Intersection', detail: 'Where the two LOPs cross is your FIX. With three LOPs you get a small triangle (cocked hat) — your true position is within it.' },
      { title: 'Refine if Needed', detail: 'If the triangle is large, re-compute with the new estimated position as the new AP and iterate. The fix usually converges in 1-2 iterations.' },
    ],
    relatedConcepts: ['lop', 'intercept', 'running-fix'],
    cameraPreset: { position: [3, 2, 4], target: [0, 0, 0] },
    visualizationKey: 'fix',
    color: '#00E676',
  },
]
