// Module 8 — Magnetic Earth
// Approximate magnetic-pole positions used throughout (they drift over time):
//   North Magnetic Pole ≈ 80° N, 110° W
//   South Magnetic Pole ≈ 64° S, 137° E

export const module8 = [
  {
    id: 'magnetic-poles',
    name: 'Magnetic Poles',
    module: 8,
    difficulty: 'basic',
    emoji: '🧲',
    description: 'Earth has two magnetic poles, near (but not at!) the geographic North and South Poles. A compass needle points toward the North Magnetic Pole. Curious fact: the "North Magnetic Pole" near Canada is technically a magnetic SOUTH pole in physics — it earned the "north" name from its geographic location, not its polarity.',
    tooltip: 'Earth acts like a giant bar magnet hidden inside it! It has a North Magnetic Pole (in the high Arctic, drifting between Canada and Siberia) and a South Magnetic Pole (in Antarctica). These are NOT the same as the geographic poles where Earth\'s spin axis comes out.\n\nFun fact: by physics convention, the "North Magnetic Pole" near the Arctic is actually a magnetic SOUTH pole. That\'s why a compass needle\'s north-seeking end is attracted to it (opposite poles attract!). The geographic naming stuck because of WHERE the poles sit, not their actual magnetic polarity.',
    analogy: 'Imagine someone shoved a giant bar magnet inside Earth, but a little crooked — it\'s tilted by about 11°. The two ends of that imaginary magnet poke out near (but not exactly at) the North and South Poles.',
    formula: null,
    relatedConcepts: ['mag-vs-geo-poles', 'magnetic-field', 'variation'],
    cameraPreset: { position: [0, 3, 5], target: [0, 0, 0] },
    visualizationKey: 'magnetic-poles',
    color: '#FF6B6B',
  },
  {
    id: 'mag-vs-geo-poles',
    name: 'Magnetic vs Geographic Poles',
    module: 8,
    difficulty: 'basic',
    emoji: '🎯',
    description: 'The Geographic Poles are where Earth\'s spin axis pokes out — exactly North and South. The Magnetic Poles are about 11° off from these. A compass points to magnetic north, NOT true north.',
    tooltip: 'Geographic North = where Earth\'s spin axis points (true north, used for maps, latitude, the celestial pole). Magnetic North = where the magnet inside Earth points. They\'re close but NOT the same. The angle between them depends on where you are on Earth — that\'s called Variation.',
    analogy: 'Think of two different "norths" — one is the top of the spinning globe (geographic), the other is where compasses think north is (magnetic). Like a clock with two minute-hands that are slightly off from each other.',
    formula: null,
    relatedConcepts: ['magnetic-poles', 'variation', 'celestial-poles'],
    cameraPreset: { position: [0, 3, 5], target: [0, 0, 0] },
    visualizationKey: 'mag-vs-geo-poles',
    color: '#FF6B6B',
  },
  {
    id: 'magnetic-field',
    name: 'Earth\'s Magnetic Field',
    module: 8,
    difficulty: 'intermediate',
    emoji: '〰️',
    description: 'Earth\'s magnetic field forms invisible loops from one magnetic pole, out into space, and back into the other pole. By convention, field arrows EMERGE from the magnetic North pole and ENTER the magnetic South pole. Because Earth\'s "N Magnetic Pole" (Arctic) is physically a south pole, external field lines actually flow from the Antarctica side toward the Arctic side.',
    tooltip: 'Earth\'s magnetic field looks like the field around a bar magnet — invisible loops emerging from one magnetic pole, sweeping out through space, and returning into the other. It surrounds Earth like a protective shield (the "magnetosphere") and shields us from harmful particles from the Sun.\n\nDirection convention: external field lines always flow FROM the magnetic NORTH pole TO the magnetic SOUTH pole. Since Earth\'s labelled "N Magnetic Pole" near Canada is actually a magnetic south, the arrows on the loops outside Earth point from the Antarctica-side pole toward the Arctic-side pole.',
    analogy: 'Sprinkle iron filings around a bar magnet on a piece of paper, and the filings line up in curving loops from N pole to S pole — that\'s exactly the shape of Earth\'s field, but spread out for thousands of kilometers around the planet.',
    formula: null,
    relatedConcepts: ['magnetic-poles', 'magnetic-meridians'],
    cameraPreset: { position: [0, 2, 6], target: [0, 0, 0] },
    visualizationKey: 'magnetic-field',
    color: '#FF6B6B',
  },
  {
    id: 'magnetic-meridians',
    name: 'Magnetic Meridians',
    module: 8,
    difficulty: 'intermediate',
    emoji: '🧭',
    description: 'A magnetic meridian is a line on Earth\'s surface along which a compass needle points perfectly straight ("along it"). They run between the magnetic poles — NOT between the geographic poles.',
    tooltip: 'Geographic meridians (on every map) connect the geographic North and South Poles — they go straight up–down. Magnetic meridians connect the magnetic North and South Poles instead, so they run at a slightly different angle. A compass needle naturally aligns along the magnetic meridian where you\'re standing.',
    analogy: 'Imagine drawing the lines that a compass needle would point along, all over Earth. Those lines (called magnetic meridians) end at the magnetic poles — not the geographic poles. They\'re tilted compared to map meridians, by about 11° at the equator.',
    formula: null,
    relatedConcepts: ['meridian', 'magnetic-poles', 'variation'],
    cameraPreset: { position: [0, 2, 5], target: [0, 0, 0] },
    visualizationKey: 'magnetic-meridians',
    color: '#FF6B6B',
  },
  {
    id: 'variation',
    name: 'Variation (Magnetic Declination)',
    module: 8,
    difficulty: 'intermediate',
    emoji: '📐',
    description: 'Variation is the angle between True North (geographic) and Magnetic North at any place on Earth. A navigator must add or subtract this angle to convert a compass reading into a true bearing.',
    tooltip: 'Variation (also called magnetic declination) is the angle between the direction your compass points (Magnetic N) and where True North actually is. It changes depending on WHERE you are on Earth. Sailors and pilots ADD or SUBTRACT this angle to convert compass headings to true headings.',
    analogy: 'Imagine you and a friend are pointing at "north" — you with a compass, your friend by looking at the North Pole on a globe. You\'ll point in slightly different directions. The gap between your fingers (in degrees) is the Variation.',
    formula: 'True bearing = Compass bearing ± Variation\n(W variation: subtract;  E variation: add)',
    relatedConcepts: ['mag-vs-geo-poles', 'true-vs-mag-direction', 'magnetic-compass'],
    cameraPreset: { position: [3, 1.5, 4], target: [0, 0, 0] },
    visualizationKey: 'variation',
    color: '#FF6B6B',
  },
  {
    id: 'magnetic-compass',
    name: 'Magnetic Compass',
    module: 8,
    difficulty: 'basic',
    emoji: '🧭',
    description: 'A magnetic compass is a small magnet (the "needle") balanced so it can swing freely. It aligns itself with Earth\'s magnetic field, pointing toward the North Magnetic Pole.',
    tooltip: 'A magnetic compass is just a tiny magnet on a pivot. The little magnet swings until it lines up with Earth\'s magnetic field — so the red end points toward the North Magnetic Pole. It\'s simple, cheap, and used for thousands of years — but it doesn\'t point at TRUE north, only at MAGNETIC north.',
    analogy: 'Think of a fridge magnet. If you balanced it on a pin so it could spin, and held it far from anything else metallic, it would slowly spin until it lined up with Earth\'s magnetic field — pointing toward the magnetic North Pole. That\'s a compass!',
    formula: null,
    relatedConcepts: ['gyro-compass', 'variation', 'true-vs-mag-direction'],
    cameraPreset: { position: [3, 1.5, 4], target: [0, 0, 0] },
    visualizationKey: 'magnetic-compass',
    color: '#FF6B6B',
  },
  {
    id: 'gyro-compass',
    name: 'Gyro Compass',
    module: 8,
    difficulty: 'intermediate',
    emoji: '⚙️',
    description: 'A gyrocompass uses a fast-spinning wheel (gyroscope) to find True North without using magnetism at all. It always points to the geographic North Pole, regardless of magnetic variations.',
    tooltip: 'A gyrocompass has a heavy wheel spinning at high speed. Because of physics (gyroscopic effect + Earth\'s rotation), the spin axis automatically settles pointing toward True North. Unlike a magnetic compass, it ignores magnetic fields entirely — it\'s always accurate, always pointing to the real (geographic) North. Big ships and planes carry one because magnetic compasses can be fooled by nearby metal or local magnetic anomalies.',
    analogy: 'A spinning toy top resists tipping over because it wants to keep spinning around the same axis. A gyrocompass uses this trick: a heavy spinning wheel "locks onto" Earth\'s rotation axis, which automatically aligns it with the True North pole.',
    formula: null,
    relatedConcepts: ['magnetic-compass', 'variation', 'celestial-poles'],
    cameraPreset: { position: [3, 1.5, 4], target: [0, 0, 0] },
    visualizationKey: 'gyro-compass',
    color: '#FFB830',
  },
  {
    id: 'true-vs-mag-direction',
    name: 'True vs Magnetic Direction',
    module: 8,
    difficulty: 'intermediate',
    emoji: '↗️',
    description: 'True direction is measured against the geographic poles (real north). Magnetic direction is what a compass shows. They differ by the local Variation. Navigators always specify which one they mean.',
    tooltip: 'There are TWO different "norths" you can use: TRUE north (the real geographic North Pole, used in maps, latitude, GPS) and MAGNETIC north (where compasses point). At your observer position, these usually differ by a few degrees. Always know which you\'re using when navigating!',
    analogy: 'It\'s like having two friends who both say "Look north!" One points at the actual North Pole on the globe (true). The other looks at a compass needle (magnetic). They point in slightly different directions — and the gap between them is the Variation at that location.',
    formula: 'True bearing − Magnetic bearing = Variation',
    relatedConcepts: ['variation', 'magnetic-compass', 'gyro-compass'],
    cameraPreset: { position: [3, 1.5, 4], target: [0, 0, 0] },
    visualizationKey: 'true-vs-mag-direction',
    color: '#FF6B6B',
  },
]
