export const module6 = [
  {
    id: 'great-circle-route',
    name: 'Great Circle Route',
    module: 6,
    difficulty: 'intermediate',
    emoji: '✈️',
    description: 'The shortest path between two points on a sphere. Crosses different meridians continuously — heading is always changing. Shorter for long distances.',
    tooltip: 'A great circle route is the shortest path between two points on Earth\'s surface. On a globe, it looks like a curved arc that bulges toward the nearest pole. It\'s the shortest because it follows the surface of the sphere along its "flattest" curve. Aircraft use great circle routes to save fuel.',
    analogy: 'On a flat map, the straight line from New York to London goes across the Atlantic. But on a globe, the shortest path curves north over Greenland! That curved route over Greenland is the great circle route — actually shorter by hundreds of miles.',
    formula: null,
    relatedConcepts: ['rhumb-line', 'great-circle', 'vertex'],
    cameraPreset: { position: [0, 4, 4], target: [0, 0, 0] },
    visualizationKey: 'great-circle-route',
    color: '#00E5FF',
  },
  {
    id: 'rhumb-line',
    name: 'Rhumb Line',
    module: 6,
    difficulty: 'intermediate',
    emoji: '⛵',
    description: 'A path that crosses every meridian at the same angle — constant compass heading. Longer than great circle but easier to steer. Straight line on Mercator charts.',
    tooltip: 'A rhumb line (loxodrome) is a course that maintains a CONSTANT compass heading. You just set your compass to one bearing and sail until you arrive. It\'s longer than a great circle route, but much easier to navigate. On a Mercator chart (like most sea charts), a rhumb line appears as a straight line.',
    analogy: 'If you drove from Los Angeles to New York by always keeping your compass pointing exactly northeast, you\'d be following a rhumb line. Simple to follow — just keep the same heading. But a great circle route (adjusting your heading as you go) would be a bit shorter.',
    formula: null,
    relatedConcepts: ['great-circle-route', 'great-circle'],
    cameraPreset: { position: [0, 3, 5], target: [0, 0, 0] },
    visualizationKey: 'rhumb-line',
    color: '#FFB830',
  },
  {
    id: 'vertex',
    name: 'Vertex of a Great Circle',
    module: 6,
    difficulty: 'advanced',
    emoji: '🏔️',
    description: 'The highest (or lowest) latitude point on a great circle route. The course is due East or West at the vertex.',
    tooltip: 'The vertex of a great circle route is the point on the route closest to the pole — its highest latitude. At the vertex, you are momentarily sailing due east or west. After the vertex, the route curves back toward lower latitudes.',
    analogy: 'A great circle route is like a mountain road that goes up, reaches the highest point (vertex), then comes back down. At the very top (vertex), the road is perfectly level (east-west). On either side, the road is going up or downhill (changing latitude).',
    formula: null,
    relatedConcepts: ['great-circle-route', 'latitude'],
    cameraPreset: { position: [0, 5, 3], target: [0, 0, 0] },
    visualizationKey: 'vertex',
    color: '#FFFFFF',
  },
]
