export const module4 = [
  {
    id: 'pzx-overview',
    name: 'The PZX Triangle',
    module: 4,
    difficulty: 'advanced',
    emoji: '🔺',
    description: 'The most important triangle in celestial navigation. Its three vertices are the Pole, your Zenith, and the celestial body. Solving it gives altitude and azimuth.',
    tooltip: 'The PZX triangle is a spherical triangle (drawn on the surface of the celestial sphere) with three special points as its corners: P (Celestial Pole), Z (your Zenith), and X (a celestial body). By solving this triangle mathematically, navigators calculate where bodies should appear in the sky.',
    analogy: 'Imagine connecting three dots on the surface of a giant ball: the "North Pole" of the ball, the point right above your head, and the position of a star. The triangle formed by those three dots IS the PZX triangle. Every piece of celestial navigation comes down to this one triangle.',
    formula: 'sin(Hc) = sin(Lat)·sin(Dec) + cos(Lat)·cos(Dec)·cos(LHA)',
    relatedConcepts: ['pzx-pole', 'pzx-zenith', 'pzx-body', 'altitude-equation'],
    cameraPreset: { position: [0, 2, 8], target: [0, 0, 0] },
    visualizationKey: 'pzx-overview',
    color: '#00E5FF',
  },
  {
    id: 'pzx-pole',
    name: 'Pole (P)',
    module: 4,
    difficulty: 'intermediate',
    emoji: '⭐',
    description: 'The elevated Celestial Pole — North or South depending on hemisphere. The apex of the navigational triangle.',
    tooltip: 'P is the Celestial Pole vertex of the PZX triangle — the North Celestial Pole if you\'re in the northern hemisphere, or the South Celestial Pole in the southern hemisphere. It\'s the "top" anchor of the triangle.',
    analogy: 'In the PZX triangle, P is like the pivot point at the top of a swing set. Everything rotates around it. The North Star sits almost exactly at P for observers in the northern hemisphere.',
    formula: null,
    relatedConcepts: ['pzx-overview', 'celestial-poles', 'pzx-colat'],
    cameraPreset: { position: [0, 5, 3], target: [0, 0, 0] },
    visualizationKey: 'pzx-pole',
    color: '#FFB830',
  },
  {
    id: 'pzx-zenith',
    name: 'Zenith (Z)',
    module: 4,
    difficulty: 'intermediate',
    emoji: '⬆️',
    description: 'Your Zenith projected onto the celestial sphere. Your "position" in the sky.',
    tooltip: 'Z is your Zenith — the point on the celestial sphere directly above your head. In the PZX triangle, Z represents YOUR position in the sky. The distance from P to Z is your co-latitude, which is directly related to your geographic latitude.',
    analogy: 'Your zenith is like your personal "you are here" marker on the celestial sphere. Different observers at different latitudes will have their Z at different heights above the celestial equator.',
    formula: null,
    relatedConcepts: ['pzx-overview', 'zenith', 'pzx-colat'],
    cameraPreset: { position: [1, 4, 3], target: [0, 0, 0] },
    visualizationKey: 'pzx-zenith',
    color: '#00E5FF',
  },
  {
    id: 'pzx-body',
    name: 'Celestial Body (X)',
    module: 4,
    difficulty: 'intermediate',
    emoji: '🌟',
    description: 'Any celestial body — Sun, Moon, planet, or star. The object whose altitude and azimuth we\'re measuring or predicting.',
    tooltip: 'X is the celestial body — any object you\'re navigating by: the Sun, Moon, a planet, or a star. In the PZX triangle, X is the third vertex. The distance from Z to X is the Zenith Distance, which corresponds to the body\'s altitude.',
    analogy: 'X marks the spot! In the PZX triangle, X is literally the "target" — the star or planet you\'re measuring. Your navigation calculation is all about figuring out how the triangle connecting you (Z), the pole (P), and the target (X) should look.',
    formula: null,
    relatedConcepts: ['pzx-overview', 'declination', 'pzx-polar-distance'],
    cameraPreset: { position: [2, 3, 5], target: [0, 0, 0] },
    visualizationKey: 'pzx-body',
    color: '#FFFFFF',
  },
  {
    id: 'pzx-colat',
    name: 'Side PZ — Co-latitude',
    module: 4,
    difficulty: 'advanced',
    emoji: '📐',
    description: 'The side from Pole to Zenith. Equals 90° minus your latitude. Also called the "co-latitude". If you\'re at 51°N, PZ = 39°.',
    tooltip: 'The PZ side of the triangle connects the Pole to your Zenith. Its length (in degrees of arc) equals 90° minus your latitude — called the "co-latitude." For an observer at 51°N, PZ = 90° − 51° = 39°. This side represents how far you are from the pole.',
    analogy: 'PZ is the "you-to-pole" side. In London (51°N), you\'re 39° away from the North Celestial Pole (90° − 51° = 39°). At the equator (0° latitude), PZ would be 90°. At the North Pole, PZ would be 0° — you\'d be standing right under the pole!',
    formula: 'PZ = 90° − Latitude',
    relatedConcepts: ['pzx-overview', 'latitude', 'pzx-polar-distance'],
    cameraPreset: { position: [0, 4, 4], target: [0, 0, 0] },
    visualizationKey: 'pzx-colat',
    color: '#FFB830',
  },
  {
    id: 'pzx-polar-distance',
    name: 'Side PX — Polar Distance',
    module: 4,
    difficulty: 'advanced',
    emoji: '📏',
    description: 'The side from Pole to the body. Equals 90° – Declination. Tells you how far the body is from the pole.',
    tooltip: 'The PX side connects the Pole to the celestial body X. Its length equals 90° minus the body\'s declination — called "polar distance." A star at the equator (0° Dec) has polar distance 90°. A star at 60°N declination has polar distance 30°.',
    analogy: 'PX is the "pole-to-star" side. Stars with high declination (close to the celestial equator\'s north side) have a SHORT PX — they\'re close to the pole. Stars near the celestial equator have LONG PX (near 90°) — they\'re far from the pole.',
    formula: 'PX = 90° − Declination',
    relatedConcepts: ['pzx-overview', 'declination', 'pzx-colat'],
    cameraPreset: { position: [0, 4, 4], target: [0, 0, 0] },
    visualizationKey: 'pzx-polar-distance',
    color: '#8B7CF8',
  },
  {
    id: 'pzx-zx',
    name: 'Side ZX — Zenith Distance',
    module: 4,
    difficulty: 'advanced',
    emoji: '↕️',
    description: 'The side from Zenith to the body. Equals the zenith distance — what we MEASURE with the sextant. This is what we solve for when calculating an intercept.',
    tooltip: 'The ZX side connects your Zenith to the celestial body. Its length equals the Zenith Distance (= 90° − altitude). This is what your sextant measurement gives you indirectly. When you observe altitude, you\'re actually measuring the ZX side of this triangle.',
    analogy: 'ZX is the "you-to-star" distance in the sky. Measuring altitude with a sextant is really measuring how long ZX is. Higher altitude = shorter ZX. When a star is at your zenith, ZX = 0°. When it\'s on the horizon, ZX = 90°.',
    formula: 'ZX = 90° − Altitude (h)',
    relatedConcepts: ['pzx-overview', 'altitude', 'zenith-distance'],
    cameraPreset: { position: [2, 3, 5], target: [0, 0, 0] },
    visualizationKey: 'pzx-zx',
    color: '#00E5FF',
  },
  {
    id: 'pzx-azimuth',
    name: 'Angle at Z — Azimuth',
    module: 4,
    difficulty: 'advanced',
    emoji: '🧭',
    description: 'The angle at the Zenith vertex of the PZX triangle equals the Azimuth of the body — the compass bearing to the body measured from North.',
    tooltip: 'The angle at vertex Z in the PZX triangle is the Azimuth — the compass bearing to the body. When you solve the PZX triangle, you calculate both the altitude (from ZX) AND the azimuth (from the Z angle). That\'s the power of the PZX triangle — two navigation outputs from one calculation.',
    analogy: 'Imagine the PZX triangle as a map. The angle at your corner (Z) tells you which direction to look for the star — that\'s the azimuth, your compass bearing to the body.',
    formula: 'cos(Z) = sin(Dec) − sin(Lat)·sin(Hc) / cos(Lat)·cos(Hc)',
    relatedConcepts: ['pzx-overview', 'azimuth', 'altitude-equation'],
    cameraPreset: { position: [3, 1, 3], target: [0, 0, 0] },
    visualizationKey: 'pzx-azimuth',
    color: '#FFB830',
  },
  {
    id: 'pzx-lha',
    name: 'Angle at P — LHA',
    module: 4,
    difficulty: 'advanced',
    emoji: '🕐',
    description: 'The angle at the Pole vertex equals the Local Hour Angle (LHA) or Meridian Angle (t). The key input to the altitude calculation formula.',
    tooltip: 'The angle at vertex P in the PZX triangle is the Local Hour Angle (LHA). LHA is the key input that changes as Earth rotates — it tells the formula "where is the body right now relative to your meridian?" This is why LHA appears in the altitude calculation formula.',
    analogy: 'The P angle is like the "time" angle — how far the body has moved from your meridian. At LHA = 0°, the body is on your meridian (noon for the Sun). As time passes, LHA grows as the body moves westward.',
    formula: 'LHA = GHA − West Longitude',
    relatedConcepts: ['pzx-overview', 'lha', 'altitude-equation'],
    cameraPreset: { position: [0, 5, 3], target: [0, 0, 0] },
    visualizationKey: 'pzx-lha',
    color: '#00E5FF',
  },
  {
    id: 'altitude-equation',
    name: 'The Altitude Equation',
    module: 4,
    difficulty: 'advanced',
    emoji: '🧮',
    description: 'The master equation: given Latitude, Declination, and LHA — compute calculated altitude (Hc) and compare to observed altitude (Ho).',
    tooltip: 'This is THE most important formula in celestial navigation! Given your latitude, a star\'s declination, and the Local Hour Angle, you can calculate exactly how high that star SHOULD be in your sky (Hc = calculated altitude). Compare Hc to what you actually observed (Ho) to get your position intercept.',
    analogy: 'It\'s like predicting where a specific basketball player should be on the court based on the play being run. If they\'re NOT where they should be (Ho ≠ Hc), you know your assumed position (the play call) was wrong and you need to adjust.',
    formula: 'sin(Hc) = sin(Lat)·sin(Dec) + cos(Lat)·cos(Dec)·cos(LHA)',
    relatedConcepts: ['pzx-overview', 'lha', 'declination', 'intercept'],
    cameraPreset: { position: [0, 2, 8], target: [0, 0, 0] },
    visualizationKey: 'altitude-equation',
    color: '#00E5FF',
  },
]
