export const module1 = [
  {
    id: 'earth',
    name: 'Earth',
    module: 1,
    difficulty: 'basic',
    emoji: '🌍',
    description: 'Our home planet — a sphere roughly 12,742 km across. Every celestial navigation calculation begins here, with your position on this surface.',
    tooltip: 'Earth is the starting point for ALL navigation. It\'s a giant sphere (almost perfectly round) spinning in space. Every direction in celestial navigation — up, down, north, south — is measured from where YOU stand on Earth.',
    analogy: 'Think of Earth like a giant basketball. You\'re a tiny ant standing on it. Celestial navigation is all about figuring out exactly which spot on the basketball you\'re standing on — using only the stars!',
    formula: null,
    relatedConcepts: ['celestial-sphere', 'observer', 'zenith'],
    cameraPreset: { position: [0, 2, 5], target: [0, 0, 0] },
    visualizationKey: 'earth',
    color: '#00E5FF',
  },
  {
    id: 'celestial-sphere',
    name: 'Celestial Sphere',
    module: 1,
    difficulty: 'basic',
    emoji: '🔮',
    description: 'An imaginary sphere of infinite radius centered on Earth. All stars are projected onto its inner surface. It\'s a navigator\'s mental model for measuring sky angles.',
    tooltip: 'Imagine a giant invisible bubble surrounding Earth like a snow globe. We PRETEND all the stars are glued to the inside of this bubble. This makes it much easier to measure angles and directions in the sky.',
    analogy: 'Think of the celestial sphere like a giant hollow ball with glow-in-the-dark stars painted on the inside. Earth sits right in the middle. Even though stars are actually at wildly different distances, we act like they\'re all the same distance away — stuck to this imaginary ball.',
    formula: null,
    relatedConcepts: ['earth', 'celestial-equator', 'celestial-poles'],
    cameraPreset: { position: [0, 2, 8], target: [0, 0, 0] },
    visualizationKey: 'celestial-sphere',
    color: '#8B7CF8',
  },
  {
    id: 'observer',
    name: 'Observer',
    module: 1,
    difficulty: 'basic',
    emoji: '🧭',
    description: 'You. Standing on Earth\'s surface. All altitude and azimuth measurements are made from your position. Drag the dot to change your location.',
    tooltip: 'YOU are the observer! In celestial navigation, everything is measured from where you\'re standing. Your position on Earth determines which stars you can see, how high they appear, and which direction they\'re in.',
    analogy: 'You\'re the center of YOUR universe when it comes to navigation. Just like how things look different depending on where you stand in a room, the sky looks completely different depending on where you stand on Earth.',
    formula: null,
    relatedConcepts: ['observer-position', 'zenith', 'horizon'],
    cameraPreset: { position: [2, 1.5, 4], target: [0, 0, 0] },
    visualizationKey: 'observer',
    color: '#00E5FF',
  },
  {
    id: 'observer-position',
    name: 'Observer Position',
    module: 1,
    difficulty: 'basic',
    emoji: '📍',
    description: 'Your exact latitude and longitude. This determines which stars you can see, when the Sun rises, and how to compute your position lines.',
    tooltip: 'Your exact address on Earth! Latitude tells you how far north or south of the equator you are (0°–90°). Longitude tells you how far east or west of Greenwich, England (0°–180°).',
    analogy: 'Think of latitude and longitude like the row and column numbers on a giant grid drawn over Earth. London is at row 51°N, column 0°. Sydney is at row 34°S, column 151°E.',
    formula: 'Position = (Latitude, Longitude)',
    relatedConcepts: ['latitude', 'longitude', 'observer'],
    cameraPreset: { position: [2, 1.5, 4], target: [0, 0, 0] },
    visualizationKey: 'observer-position',
    color: '#00E5FF',
  },
  {
    id: 'zenith',
    name: 'Zenith',
    module: 1,
    difficulty: 'basic',
    emoji: '⬆️',
    description: 'The point directly overhead. If you held a plumb line and reversed it, it would point to your zenith. Every altitude measurement is measured from the horizon toward the zenith.',
    tooltip: 'Look straight up — that\'s your zenith! It\'s the point in the sky directly above your head. Imagine shooting a laser beam straight up from the top of your head — where it hits the celestial sphere is your zenith.',
    analogy: 'When you lie on your back in the grass and look straight up, you\'re staring at your zenith. Everyone on Earth has a different zenith because everyone is at a different spot on the globe.',
    formula: null,
    relatedConcepts: ['nadir', 'horizon', 'altitude', 'zenith-distance'],
    cameraPreset: { position: [1, 4, 3], target: [0, 1, 0] },
    visualizationKey: 'zenith',
    color: '#00E5FF',
  },
  {
    id: 'nadir',
    name: 'Nadir',
    module: 1,
    difficulty: 'basic',
    emoji: '⬇️',
    description: 'The point directly beneath you — the opposite of the Zenith. Passes through the center of Earth. You can\'t see it, but it\'s the anchor of your vertical line.',
    tooltip: 'The nadir is the exact opposite of your zenith — it\'s the point directly BELOW your feet, through the center of Earth. If you dug straight down forever, you\'d be heading toward your nadir.',
    analogy: 'Stand on Earth and point up — that\'s the zenith. Now point down through the ground — that\'s the nadir. They\'re always on exactly opposite sides of the celestial sphere.',
    formula: null,
    relatedConcepts: ['zenith', 'vertical-circle'],
    cameraPreset: { position: [1, -2, 4], target: [0, -1, 0] },
    visualizationKey: 'nadir',
    color: '#FF6B6B',
  },
  {
    id: 'horizon',
    name: 'Horizon',
    module: 1,
    difficulty: 'basic',
    emoji: '🌅',
    description: 'The horizontal boundary of your sky. The Rational (or Celestial) Horizon is the great circle plane through Earth\'s center, perpendicular to your Zenith line.',
    tooltip: 'The horizon is the flat circle boundary between sky and ground. Navigators use the "rational horizon" — an imaginary flat plane slicing through Earth\'s center, perfectly level where you\'re standing. Stars above this plane are visible; stars below it are not.',
    analogy: 'On a ship at sea, you can see the horizon — the circle where the sea meets the sky. The navigator\'s "rational horizon" is like a perfect, invisible version of that, extending right through the center of Earth.',
    formula: null,
    relatedConcepts: ['zenith', 'altitude', 'azimuth'],
    cameraPreset: { position: [3, 0.5, 4], target: [0, 0, 0] },
    visualizationKey: 'horizon',
    color: '#00E5FF',
  },
  {
    id: 'celestial-equator',
    name: 'Celestial Equator',
    module: 1,
    difficulty: 'basic',
    emoji: '🔵',
    description: 'Earth\'s equator projected outward onto the celestial sphere. Declination is measured north and south from this circle. It\'s the celestial equivalent of 0° latitude.',
    tooltip: 'Take Earth\'s equator and imagine projecting it outward into space, all the way to the celestial sphere. That\'s the celestial equator! It divides the sky into a northern half and a southern half.',
    analogy: 'Just like how Earth\'s equator is an imaginary line dividing Earth into northern and southern halves, the celestial equator divides the sky into top and bottom halves. The Sun crosses this line twice a year — at the spring and fall equinoxes.',
    formula: null,
    relatedConcepts: ['celestial-poles', 'declination', 'celestial-sphere'],
    cameraPreset: { position: [0, 2, 8], target: [0, 0, 0] },
    visualizationKey: 'celestial-equator',
    color: '#FFFFFF',
  },
  {
    id: 'celestial-poles',
    name: 'Celestial Poles',
    module: 1,
    difficulty: 'basic',
    emoji: '⭐',
    description: 'The points where Earth\'s rotation axis, extended outward, pierces the celestial sphere. The North Celestial Pole is near Polaris. Stars appear to rotate around these points.',
    tooltip: 'Imagine extending Earth\'s spin axis (the imaginary line that Earth rotates around) far out into space. The two points where this axis pokes through the celestial sphere are the North and South Celestial Poles. The North Celestial Pole is very close to Polaris (the North Star)!',
    analogy: 'Watch a spinning top — it spins around an invisible axis. Earth is like that top. Extend that axis up through the sky and you get the North Celestial Pole, near Polaris. That\'s why Polaris barely seems to move at night while all other stars circle around it.',
    formula: null,
    relatedConcepts: ['celestial-equator', 'circumpolar-star', 'meridian'],
    cameraPreset: { position: [0, 5, 3], target: [0, 0, 0] },
    visualizationKey: 'celestial-poles',
    color: '#FFB830',
  },
  {
    id: 'meridian',
    name: 'Meridian',
    module: 1,
    difficulty: 'intermediate',
    emoji: '📏',
    description: 'Your meridian is the great circle passing through your zenith and the poles. The Sun crosses it at local noon — and that\'s exactly when you take your noon sight.',
    tooltip: 'Your meridian is an imaginary line running from the North Celestial Pole, through your zenith, all the way down to the South Celestial Pole. When the Sun crosses your meridian, that\'s local noon — the Sun is exactly due South (or North) and at its highest point.',
    analogy: 'Think of the meridian like your personal north-south line drawn across the sky. It\'s like if you held a giant protractor and drew a half-circle from due north on your horizon, up over your head, and down to due south.',
    formula: null,
    relatedConcepts: ['prime-meridian', 'lha', 'lan'],
    cameraPreset: { position: [3, 2, 3], target: [0, 0, 0] },
    visualizationKey: 'meridian',
    color: '#FFB830',
  },
  {
    id: 'prime-meridian',
    name: 'Prime Meridian',
    module: 1,
    difficulty: 'basic',
    emoji: '🏴',
    description: 'The 0° reference meridian through Greenwich, England. The Prime Celestial Meridian passes through the First Point of Aries — the reference for measuring GHA and SHA.',
    tooltip: 'The prime meridian is Earth\'s "starting line" for measuring longitude. It runs through the Royal Observatory in Greenwich, London. By international agreement, this is 0° longitude — everything else is measured east or west from here.',
    analogy: 'Every game needs a starting line. In soccer, you start from the center circle. In measuring longitude, we start from Greenwich, England. Someone had to pick a starting point, and in 1884, the world agreed on Greenwich!',
    formula: null,
    relatedConcepts: ['meridian', 'longitude', 'gha'],
    cameraPreset: { position: [-3, 1, 4], target: [0, 0, 0] },
    visualizationKey: 'prime-meridian',
    color: '#00E676',
  },
  {
    id: 'celestial-hemisphere',
    name: 'Celestial Hemisphere',
    module: 1,
    difficulty: 'basic',
    emoji: '🌐',
    description: 'The half of the celestial sphere you can see above your horizon. Stars in the lower hemisphere are below the horizon and invisible.',
    tooltip: 'The celestial hemisphere is the half of the sky dome that you can actually see — everything above your horizon. The other half is blocked by Earth itself. The higher your zenith is in the dome, the more of the sky you can see.',
    analogy: 'Imagine the celestial sphere is a full soccer ball. Your horizon cuts it exactly in half. You can only see the top half — the upper celestial hemisphere. The bottom half is below ground, hidden by Earth.',
    formula: null,
    relatedConcepts: ['horizon', 'zenith', 'celestial-sphere'],
    cameraPreset: { position: [0, 3, 6], target: [0, 0, 0] },
    visualizationKey: 'celestial-hemisphere',
    color: '#8B7CF8',
  },
]
